ORDER_STATUS_MESSAGES = {
    "0": "Seller cancel order",
    "3": "Order Reject Due Empty Stock",
    "5": "Order Canceled by Fraud",
    "6": "Order Rejected (Auto Cancel Out of Stock)",
    "10": "Order rejected by seller",
    "15": "Instant Cancel by Buyer",
    "100": "Order Created",
    "103": "Wait for payment confirmation from third party",
    "220": "Pending Seller Accept",
    "221": "Waiting for partner approval",
    "400": "Seller Accept Order",
    "450": "Waiting for pickup",
    "500": "In Progress Shipment",
    "501": "Status changed to waiting resi have no input",
    "520": "Invalid shipment reference number (AWB)",
    "530": "Requested by user to correct invalid entry of shipment reference number",
    "540": "Delivered to Pickup Point",
    "550": "Return to Seller",
    "600": "Order delivered",
    "601": "Buyer open a case to finish an order",
    "690": "Fraud Review",
    "700": "Order finished"
}